/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 04:08:00 GMT 2026
 */

package edu.colostate.cs415.evosuite;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

import java.util.LinkedHashSet;
import java.util.Set;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.model.Company;
import edu.colostate.cs415.model.Project;
import edu.colostate.cs415.model.ProjectSize;
import edu.colostate.cs415.model.ProjectStatus;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Company_ESTest extends Company_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Company company0 = new Company("&$");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("O5W'");
      linkedHashSet0.add(qualification0);
      company0.createWorker("O5W'", linkedHashSet0, 0.0);
      Set<Worker> set0 = company0.getUnassignedWorkers();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Company company0 = new Company("Hm4SAg:tU/i.=v@");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("Hm4SAg:tU/i.=v@");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      company0.createProject("Hm4SAg:tU/i.=v@", linkedHashSet0, projectSize0);
      Set<Project> set0 = company0.getProjects();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Company company0 = new Company(", missig@u;lifications='");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createQualification(", missig@u;lifications='");
      Worker worker0 = company0.createWorker("}9", set0, 1663.9);
      Set<Worker> set1 = company0.getEmployedWorkers();
      assertTrue(set1.contains(worker0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Company company0 = new Company("&$");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("O5W'");
      linkedHashSet0.add(qualification0);
      company0.createWorker("O5W'", linkedHashSet0, 0.0);
      Set<Worker> set0 = company0.getAvailableWorkers();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification(".eM}$d/");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      Worker worker0 = company0.createWorker("Fws4", linkedHashSet0, 1.0);
      company0.assign(worker0, project0);
      Set<Worker> set0 = company0.getAssignedWorkers();
      assertTrue(set0.contains(worker0));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification(".eM}$d/");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      // Undeclared exception!
      try { 
        company0.createProject("", linkedHashSet0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project name cannot be empty
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Company company0 = new Company("&$");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("O5W'");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("O5W'", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Ss_*R", linkedHashSet0, projectSize0);
      project0.addWorker(worker0);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker must belong to Project and Worker must be assigned Project
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification("Worker and Project must belong to Company");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Worker worker0 = company0.createWorker("Fws4", linkedHashSet0, 1.0);
      Project project0 = new Project("Pg3':Id1nnA]q`^", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      company0.unassignAll(worker0);
      assertEquals(12, Worker.MAX_WORKLOAD);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Company company0 = new Company("?5*0^|X?2p|eR 1u(2E");
      company0.createQualification("?5*0^|X?2p|eR 1u(2E");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = new Worker("?5*0^|X?2p|eR 1u(2E", set0, 0.0);
      // Undeclared exception!
      try { 
        company0.unassignAll(worker0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Company company0 = new Company("1:_Ox|?H<*Ey(WQ");
      // Undeclared exception!
      try { 
        company0.unassignAll((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification(".eM}$d/");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      Worker worker0 = company0.createWorker("Fws4", linkedHashSet0, 1.0);
      Project project1 = company0.createProject("|&s", linkedHashSet0, projectSize0);
      worker0.addProject(project1);
      company0.assign(worker0, project0);
      // Undeclared exception!
      try { 
        company0.unassignAll(worker0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker must belong to Project and Worker must be assigned Project
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Company company0 = new Company("&$");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("&$");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("&$", linkedHashSet0, 3.692452249283267);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Ss_*R", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker must belong to Project and Worker must be assigned Project
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Company company0 = new Company(", missig@u;lifications='");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createQualification(", missig@u;lifications='");
      Worker worker0 = company0.createWorker("}9", set0, 1664.7386470151748);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("H", set0, projectSize0);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker and Project must belong to Company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Company company0 = new Company("&$");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("O5W'");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("&$", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("&$", linkedHashSet0, 12);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker and Project must belong to Company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Company company0 = new Company("&$");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("O5W'");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("O5W'", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker or Project cannot be null
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Company company0 = new Company("Hm4SAg:tU/i.=v@");
      // Undeclared exception!
      try { 
        company0.unassign((Worker) null, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker or Project cannot be null
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification("Worker and Project must belong to Company");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      Worker worker0 = company0.createWorker("Worker and Project must belong to Company", linkedHashSet0, 1355.1045211388496);
      project0.addWorker(worker0);
      Worker worker1 = company0.createWorker("Fws4", linkedHashSet0, 1.0);
      company0.assign(worker1, project0);
      assertEquals("Worker and Project must belong to Company", company0.getName());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification(".eM}$d/");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      Worker worker0 = company0.createWorker("Fws4", linkedHashSet0, 1.0);
      ProjectStatus projectStatus0 = ProjectStatus.ACTIVE;
      project0.setStatus(projectStatus0);
      company0.finish(project0);
      company0.assign(worker0, project0);
      assertEquals(ProjectStatus.FINISHED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification(".eM}$d/");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      Worker worker0 = company0.createWorker("Worker and Project must belong to Company:0:1", linkedHashSet0, 1.0);
      project0.addWorker(worker0);
      company0.start(project0);
      project0.removeWorker(worker0);
      company0.assign(worker0, project0);
      assertEquals(ProjectStatus.ACTIVE, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification("Worker and Project must belong to Company");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      Worker worker0 = company0.createWorker("Fws4", linkedHashSet0, 1.0);
      project0.addWorker(worker0);
      company0.assign(worker0, project0);
      assertEquals("Worker and Project must belong to Company", project0.getName());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Company company0 = new Company("&$");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("O5W'");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("O5W'", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("&$", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        company0.assign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker or Project does not belong to
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Company company0 = new Company("1:_Ox|?H<*Ey(WQ");
      company0.createQualification("1:_Ox|?H<*Ey(WQ");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Woker or Project does not belog to", set0, projectSize0);
      Worker worker0 = new Worker("Woker or Project does not belog to", set0, 0.583);
      // Undeclared exception!
      try { 
        company0.assign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker or Project does not belong to
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification(".eM}$d/");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("Fws4", linkedHashSet0, 1.0);
      // Undeclared exception!
      try { 
        company0.assign(worker0, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot assign a null worker or project
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Company company0 = new Company("=OaT");
      // Undeclared exception!
      try { 
        company0.assign((Worker) null, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot assign a null worker or project
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification("Worker and Project must bel%ng to Company");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      Worker worker0 = company0.createWorker("Worker and Project must belong to Company:0:1", linkedHashSet0, 1.0);
      project0.addWorker(worker0);
      company0.start(project0);
      // Undeclared exception!
      try { 
        company0.finish(project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker must belong to Project and Worker must be assigned Project
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      String string0 = "P#Zr\\oi\\u)";
      Company company0 = new Company(string0);
      Company company1 = new Company("7>hKif.`(pqKx");
      company1.createQualification(string0);
      Set<Qualification> set0 = company1.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company1.createProject("MJa]|ICasvkM", set0, projectSize0);
      // Undeclared exception!
      try { 
        company0.finish(project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot finish a null project or one that does not belong to company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification("Worker and Project must bel%ng to Company");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      company0.finish(project0);
      assertEquals(ProjectStatus.PLANNED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Company company0 = new Company("P#ZroiN)@");
      // Undeclared exception!
      try { 
        company0.finish((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot finish a null project or one that does not belong to company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification(".eM}$d/");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      Worker worker0 = company0.createWorker("Fws4", linkedHashSet0, 1.0);
      project0.addWorker(worker0);
      company0.start(project0);
      worker0.addProject(project0);
      company0.unassignAll(worker0);
      company0.start(project0);
      assertEquals(ProjectStatus.SUSPENDED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification(".eM}$d/");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.ACTIVE;
      project0.setStatus(projectStatus0);
      company0.start(project0);
      assertEquals("Worker and Project must belong to Company", project0.getName());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Company company0 = new Company("}bDHkv2-3@XQ#N}W|%;");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createQualification("}bDHkv2-3@XQ#N}W|%;");
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("}bDHkv2-3@XQ#N}W|%;", set0, projectSize0);
      // Undeclared exception!
      try { 
        company0.start(project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Company company0 = new Company("JO?\u0000h2$P-?Q>h_q");
      // Undeclared exception!
      try { 
        company0.start((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = new Qualification("Worker and Project must belong to Company");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("Worker and Project must belong to Company", linkedHashSet0, projectSize0);
      assertNull(project0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Company company0 = new Company("Hm4SAg:tU/i.=v@");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Project project0 = company0.createProject("Hm4SAg:tU/i.=v@", linkedHashSet0, (ProjectSize) null);
      assertNull(project0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Company company0 = new Company("edu.colostate.cs415.model.ProjectSize");
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("", (Set<Qualification>) null, projectSize0);
      assertNull(project0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Company company0 = new Company("djJ!D\"N.h");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject((String) null, set0, projectSize0);
      assertNull(project0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Company company0 = new Company("edu.colostate.cs415.model.ProjectSize");
      Qualification qualification0 = company0.createQualification("");
      assertNull(qualification0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Company company0 = new Company("aC#F7X,n:,");
      Qualification qualification0 = company0.createQualification((String) null);
      assertNull(qualification0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Company company0 = new Company("Hm4SAg:tU/i.=v@");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Hm4SAg:tU/i.=v@");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("Hm4SAg:tU/i.=v@", linkedHashSet0, 1310.8);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Company company0 = new Company("Hm4SAgtUn/i.=v@");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("Hm4SAgtUn/i.=v@");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("Hm4SAgtUn/i.=v@", linkedHashSet0, (-1230.7422117));
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Company company0 = new Company("=OaT");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("=OaT", set0, (-0.03843412989109529));
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Company company0 = new Company("edu.colostate.cs415.model.ProjectSize");
      Worker worker0 = company0.createWorker("edu.colostate.cs415.model.ProjectSize", (Set<Qualification>) null, 1356.388107365774);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Company company0 = new Company("Worker or Project does not belong to");
      Worker worker0 = company0.createWorker("", (Set<Qualification>) null, (-1855.99329766));
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Company company0 = new Company("1:_Ox|?H<*Ey(WQ");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker((String) null, set0, (-379.824399));
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(0);
      Qualification qualification0 = company0.createQualification("Worker and Project must bel%ng to Company");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("Worker and Project must belong to Company:0:1", linkedHashSet0, 1.0);
      assertNotNull(worker0);
      
      Set<Worker> set0 = company0.getUnavailableWorkers();
      assertFalse(set0.contains(worker0));
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      Company company1 = new Company("Worker and Project must bel%ng to Company");
      boolean boolean0 = company0.equals(company1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Company company0 = new Company("edu.colostate.cs415.model.ProjectSize");
      boolean boolean0 = company0.equals(company0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Company company0 = null;
      try {
        company0 = new Company("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Company company0 = null;
      try {
        company0 = new Company((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Company company0 = new Company("djJ!D\"N.h");
      Set<Worker> set0 = company0.getAvailableWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      Set<Project> set0 = company0.getProjects();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Company company0 = new Company("Worker and Project must belong to Company");
      Set<Worker> set0 = company0.getAssignedWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Company company0 = new Company("1:_Ox|?H<*Ey(WQ");
      company0.hashCode();
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Company company0 = new Company("djJ!D\"N.h");
      Set<Worker> set0 = company0.getUnassignedWorkers();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Company company0 = new Company("djJ!D\"N.h");
      String string0 = company0.toString();
      assertEquals("djJ!D\"N.h:0:0", string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Company company0 = new Company("1:_Ox|?H<*Ey(WQ");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("Woker or Project does not belog to", set0, projectSize0);
      boolean boolean0 = company0.equals(project0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Company company0 = new Company("&$");
      Set<Worker> set0 = company0.getEmployedWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Company company0 = new Company("1:_Ox|?H<*Ey(WQ");
      String string0 = company0.getName();
      assertEquals("1:_Ox|?H<*Ey(WQ", string0);
  }
}
