/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 13 20:19:52 GMT 2026
 */

package edu.colostate.cs415.evosuite;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

import java.util.LinkedHashSet;
import java.util.Set;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.model.Company;
import edu.colostate.cs415.model.Project;
import edu.colostate.cs415.model.ProjectSize;
import edu.colostate.cs415.model.ProjectStatus;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Company_ESTest extends Company_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      company0.createQualification("RSnK:2/*|*");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker(",eyN-*)Vd]F[", set0, 0.0);
      Set<Worker> set1 = company0.getUnassignedWorkers();
      assertTrue(set1.contains(worker0));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      company0.createQualification("RSnK:2/*|*");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      company0.createProject(",eyN-*)Vd]F[", set0, projectSize0);
      Set<Project> set1 = company0.getProjects();
      assertEquals(1, set1.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Company company0 = new Company("17S<h]7b-ai");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("17S<h]7b-ai");
      linkedHashSet0.add(qualification0);
      company0.createWorker("17S<h]7b-ai", linkedHashSet0, 0.0);
      Set<Worker> set0 = company0.getEmployedWorkers();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      company0.createQualification("RSnK:2/*|*");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createWorker(",eyN-*)Vd]F[", set0, 0.0);
      Set<Worker> set1 = company0.getAvailableWorkers();
      assertFalse(set1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Company company0 = new Company("edu.colostate.cs415.model.Qualification");
      company0.createQualification("A Worker name cannot be empty or only whitespaces");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      // Undeclared exception!
      try { 
        company0.createProject("", set0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project name cannot be empty
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Company company0 = new Company("R");
      company0.createQualification("1[S+.D'`*wh]+YB");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("1[S+.D'`*wh]+YB", set0, projectSize0);
      Worker worker0 = company0.createWorker("6\"\"OLT/x:B/(CU5", set0, 0.0);
      company0.assign(worker0, project0);
      company0.unassign(worker0, project0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Company company0 = new Company("bCe+RBQzQr!-Kc{");
      Set<Project> set0 = company0.getProjects();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Company company0 = new Company("q9jFh_MI");
      String string0 = company0.getName();
      assertEquals("q9jFh_MI", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Company company0 = new Company("qStM_*BBd)9gv?(=i");
      company0.createQualification("qStM_*BBd)9gv?(=i");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = new Worker("qStM_*BBd)9gv?(=i", set0, 12.0);
      // Undeclared exception!
      try { 
        company0.unassignAll(worker0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Company company0 = new Company("R");
      // Undeclared exception!
      try { 
        company0.unassignAll((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Company company0 = new Company("R");
      company0.createQualification("1[S+.D'`*wh]+YB");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("1[S+.D'`*wh]+YB", set0, projectSize0);
      Worker worker0 = company0.createWorker("6\"\"OLT/x:B/(CU5", set0, 0.0);
      company0.assign(worker0, project0);
      company0.unassignAll(worker0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      company0.createQualification(",eyN-*)Vd]F[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Worker worker0 = company0.createWorker(",eyN-*)Vd]F[", set0, 0.0);
      Project project0 = company0.createProject(",eyN-*)Vd]F[", set0, projectSize0);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker must belong to Project and Worker must be assigned Project
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Company company0 = new Company(", workers='");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = company0.createQualification(", workers='");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project(", workers='", linkedHashSet0, projectSize0);
      Worker worker0 = company0.createWorker(", workers='", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker and Project must belong to Company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Company company0 = new Company("17S<h]7b-ai");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = company0.createQualification("17S<h]7b-ai");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("17S<h]7b-ai", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("17S<h]7b-ai", linkedHashSet0, 0.4505789317432009);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker and Project must belong to Company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Company company0 = new Company("wJ7g8E<~`&'xE0\".zY)");
      company0.createQualification("wJ7g8E<~`&'xE0\".zY)");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("wJ7g8E<~`&'xE0\".zY)", set0, 1051.40277889);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker or Project cannot be null
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Company company0 = new Company("_gr@Uq,vH>yEn> ");
      // Undeclared exception!
      try { 
        company0.unassign((Worker) null, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker or Project cannot be null
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Company company0 = new Company("R");
      company0.createQualification("1[S+.D'`*wh]+YB");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("1[S+.D'`*wh]+YB", set0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      Worker worker0 = company0.createWorker("6\"\"OLT/x:B/(CU5", set0, 0.0);
      company0.assign(worker0, project0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Company company0 = new Company("R");
      company0.createQualification("1[S+.D'`*wh]+YB");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("1[S+.D'`*wh]+YB", set0, projectSize0);
      Worker worker0 = company0.createWorker("6\"\"OLT/x:B/(CU5", set0, 0.0);
      company0.assign(worker0, project0);
      company0.assign(worker0, project0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      company0.createQualification("RSnK:2/*|*");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Worker worker0 = company0.createWorker(",eyN-*)Vd]F[", set0, 0.0);
      assertNotNull(worker0);
      
      Project project0 = company0.createProject(",eyN-*)Vd]F[", set0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.ACTIVE;
      project0.setStatus(projectStatus0);
      company0.assign(worker0, project0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Company company0 = new Company("E4]mQbv/1sGL3");
      Qualification qualification0 = company0.createQualification("E4]mQbv/1sGL3");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("n&-qZj![DU?>Y", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("n_y8)I[38vBp?M|`M<", linkedHashSet0, 0.6784044516383265);
      // Undeclared exception!
      try { 
        company0.assign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker and Project must belong to the company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Company company0 = new Company("qStM_*BBd)9gv?(=i");
      company0.createQualification("qStM_*BBd)9gv?(=i");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = new Worker("qStM_*BBd)9gv?(=i", set0, 12.0);
      // Undeclared exception!
      try { 
        company0.assign(worker0, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot assign a null worker or project
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Company company0 = new Company("Project qualifications cannot be null or empty");
      // Undeclared exception!
      try { 
        company0.assign((Worker) null, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot assign a null worker or project
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Company company0 = new Company("MEnJjezvY~");
      company0.createQualification("MEnJjezvY~:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("MEnJjezvY~:0:0", set0, projectSize0);
      Worker worker0 = company0.createWorker("MEnJjezvY~:0:0", set0, 0.4505789317432009);
      project0.addWorker(worker0);
      company0.start(project0);
      // Undeclared exception!
      try { 
        company0.finish(project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker must belong to Project and Worker must be assigned Project
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      company0.createQualification("RSnK:2/*|*");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject(",eyN-*)Vd]F[", set0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.ACTIVE;
      project0.setStatus(projectStatus0);
      company0.finish(project0);
      assertEquals(ProjectStatus.FINISHED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Company company0 = new Company("MEnJjezvY~");
      company0.createQualification("ENUM$VALUES");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("ENUM$VALUES", set0, projectSize0);
      // Undeclared exception!
      try { 
        company0.finish(project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot finish a null project or one that does not belong to company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      company0.createQualification("RSnK:2/*|*");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject(",eyN-*)Vd]F[", set0, projectSize0);
      company0.finish(project0);
      assertEquals(ProjectStatus.PLANNED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Company company0 = new Company("#5720TDF>\"F2F=m7G");
      // Undeclared exception!
      try { 
        company0.finish((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot finish a null project or one that does not belong to company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Company company0 = new Company("R");
      company0.createQualification("1[S+.D'`*wh]+YB");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("1[S+.D'`*wh]+YB", set0, projectSize0);
      Worker worker0 = company0.createWorker("6\"\"OLT/x:B/(CU5", set0, 0.0);
      company0.assign(worker0, project0);
      company0.start(project0);
      company0.unassignAll(worker0);
      assertEquals("6\"\"OLT/x:B/(CU5", worker0.getName());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      company0.createQualification("RSnK:2/*|*");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject(",eyN-*)Vd]F[", set0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.SUSPENDED;
      project0.setStatus(projectStatus0);
      company0.start(project0);
      assertEquals(ProjectStatus.SUSPENDED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      company0.createQualification(",eyN-*)Vd]F[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject(",eyN-*)Vd]F[", set0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.ACTIVE;
      project0.setStatus(projectStatus0);
      company0.start(project0);
      assertEquals(ProjectSize.SMALL, project0.getSize());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Company company0 = new Company("17S<h]7b-ai");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = company0.createQualification("17S<h]7b-ai");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("17S<h]7b-ai", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        company0.start(project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Company company0 = new Company(":");
      // Undeclared exception!
      try { 
        company0.start((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Company company0 = new Company("Project qualifications cannot be null or empty");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("Project qualifications cannot be null or empty");
      linkedHashSet0.add(qualification0);
      Company company1 = new Company(",ETgxm0ey");
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company1.createProject(",ETgxm0ey", linkedHashSet0, projectSize0);
      assertNull(project0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Company company0 = new Company(":");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("::0:0", set0, projectSize0);
      assertNull(project0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Company company0 = new Company("R");
      Set<Qualification> set0 = company0.getQualifications();
      Project project0 = company0.createProject("$BlU", set0, (ProjectSize) null);
      assertNull(project0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Company company0 = new Company("_gr@Uq,vH>yEn> ");
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("_gr@Uq,vH>yEn> ", (Set<Qualification>) null, projectSize0);
      assertNull(project0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Company company0 = new Company("R");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject((String) null, set0, projectSize0);
      assertNull(project0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Company company0 = new Company("A Worker salary cannot be negative or NaN value");
      Qualification qualification0 = company0.createQualification("");
      assertNull(qualification0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Company company0 = new Company("edu.colostate.cs415.model.Qualification");
      Qualification qualification0 = company0.createQualification((String) null);
      assertNull(qualification0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Company company0 = new Company("17S<h]7b-ai");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker name cannot be null");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("17S<h]7b-ai", linkedHashSet0, 1.0);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      company0.createQualification(",eyN-*)Vd]F[");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createWorker(";bHma@?K*", set0, (-1.0));
      assertFalse(set0.isEmpty());
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Company company0 = new Company("Worker can't be null");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("Worker can't be null", set0, 0.0);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Company company0 = new Company(":");
      Worker worker0 = company0.createWorker(":", (Set<Qualification>) null, (-1615.414924589231));
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Company company0 = new Company("R");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("", set0, 1729.39838);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Company company0 = new Company("bOim%k+7G||F[Lv");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker((String) null, set0, 0.0);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Company company0 = new Company("17S<h]7b-ai");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("17S<h]7b-ai");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("17S<h]7b-ai", linkedHashSet0, 0.0);
      assertNotNull(worker0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
      
      Set<Worker> set0 = company0.getUnavailableWorkers();
      assertFalse(set0.contains(worker0));
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Company company0 = new Company("Worke or Projct hnt h null");
      Company company1 = new Company("Project name cannot be null");
      boolean boolean0 = company0.equals(company1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      Object object0 = new Object();
      boolean boolean0 = company0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Company company0 = null;
      try {
        company0 = new Company("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Company company0 = null;
      try {
        company0 = new Company((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      Set<Worker> set0 = company0.getAvailableWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Company company0 = new Company("MEnJjezvY~");
      Set<Worker> set0 = company0.getAssignedWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Company company0 = new Company("q9jFh_MI");
      company0.hashCode();
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      Set<Worker> set0 = company0.getUnassignedWorkers();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Company company0 = new Company(":");
      String string0 = company0.toString();
      assertEquals("::0:0", string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Company company0 = new Company(",eyN-*)Vd]F[");
      Set<Worker> set0 = company0.getEmployedWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Company company0 = new Company("D-J/CT2^");
      boolean boolean0 = company0.equals(company0);
      assertTrue(boolean0);
  }
}
