/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 04:06:52 GMT 2026
 */

package edu.colostate.cs415.evosuite;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

import java.util.LinkedHashSet;
import java.util.Set;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.dto.QualificationDTO;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Qualification_ESTest extends Qualification_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Qualification qualification0 = new Qualification("A|xl>");
      qualification0.hashCode();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Qualification qualification0 = new Qualification("A|xl>");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Worker can't be null", linkedHashSet0, 0.0);
      qualification0.addWorker(worker0);
      Set<Worker> set0 = qualification0.getWorkers();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Qualification qualification0 = new Qualification("Worker can't be null");
      boolean boolean0 = qualification0.equals(qualification0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Qualification qualification0 = null;
      try {
        qualification0 = new Qualification((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null is not a valid description
         //
         verifyException("edu.colostate.cs415.model.Qualification", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Qualification qualification0 = new Qualification("+89J,z!ZcB");
      // Undeclared exception!
      try { 
        qualification0.removeWorker((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker can't be null
         //
         verifyException("edu.colostate.cs415.model.Qualification", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Qualification qualification0 = new Qualification("d");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("d", linkedHashSet0, 0.0);
      qualification0.removeWorker(worker0);
      assertEquals("d", qualification0.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Qualification qualification0 = new Qualification("v_cuH\"3L_jay;r.(C%I");
      // Undeclared exception!
      try { 
        qualification0.addWorker((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker can't be null
         //
         verifyException("edu.colostate.cs415.model.Qualification", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Qualification qualification0 = new Qualification("d");
      boolean boolean0 = qualification0.equals("d");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Qualification qualification0 = new Qualification("d");
      Qualification qualification1 = new Qualification("d");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("d", linkedHashSet0, 0.0);
      worker0.addQualification(qualification1);
      assertEquals(1, linkedHashSet0.size());
      assertTrue(qualification1.equals((Object)qualification0));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Qualification qualification0 = null;
      try {
        qualification0 = new Qualification("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null is not a valid description
         //
         verifyException("edu.colostate.cs415.model.Qualification", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Qualification qualification0 = new Qualification("d");
      QualificationDTO qualificationDTO0 = qualification0.toDTO();
      assertEquals("d", qualificationDTO0.getDescription());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Qualification qualification0 = new Qualification("d");
      Set<Worker> set0 = qualification0.getWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Qualification qualification0 = new Qualification("d");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("d", linkedHashSet0, 0.0);
      qualification0.addWorker(worker0);
      qualification0.removeWorker(worker0);
      assertEquals("d", qualification0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Qualification qualification0 = new Qualification("d");
      String string0 = qualification0.toString();
      assertEquals("d", string0);
  }
}
