/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 13 20:18:36 GMT 2026
 */

package edu.colostate.cs415.evosuite;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

import java.util.LinkedHashSet;
import java.util.Set;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.dto.QualificationDTO;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Qualification_ESTest extends Qualification_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Qualification qualification0 = new Qualification("t");
      Qualification qualification1 = new Qualification("t");
      boolean boolean0 = qualification0.equals(qualification1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Qualification qualification0 = new Qualification("{ description='");
      qualification0.hashCode();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Qualification qualification0 = new Qualification("lP] SJ@Z6K\"*L>Wov%");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("lP] SJ@Z6K\"*L>Wov%", linkedHashSet0, 1488.2574682767674);
      qualification0.addWorker(worker0);
      Set<Worker> set0 = qualification0.getWorkers();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Qualification qualification0 = null;
      try {
        qualification0 = new Qualification((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null is not a valid description
         //
         verifyException("edu.colostate.cs415.model.Qualification", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Qualification qualification0 = new Qualification("{ description='");
      // Undeclared exception!
      try { 
        qualification0.removeWorker((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker can't be null
         //
         verifyException("edu.colostate.cs415.model.Qualification", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Qualification qualification0 = new Qualification("lP] SJ@Z6K\"*L>Wov%");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("lP] SJ@Z6K\"*L>Wov%", linkedHashSet0, 1488.2574682767674);
      qualification0.removeWorker(worker0);
      assertEquals("lP] SJ@Z6K\"*L>Wov%", qualification0.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Qualification qualification0 = new Qualification("9t");
      // Undeclared exception!
      try { 
        qualification0.addWorker((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker can't be null
         //
         verifyException("edu.colostate.cs415.model.Qualification", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Qualification qualification0 = new Qualification("lP] SJ@Z6K\"*L>Wov%");
      boolean boolean0 = qualification0.equals("lP] SJ@Z6K\"*L>Wov%");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Qualification qualification0 = null;
      try {
        qualification0 = new Qualification("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null is not a valid description
         //
         verifyException("edu.colostate.cs415.model.Qualification", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Qualification qualification0 = new Qualification("gL");
      QualificationDTO qualificationDTO0 = qualification0.toDTO();
      assertEquals("gL", qualificationDTO0.getDescription());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Qualification qualification0 = new Qualification("lP] SJ@Z6K\"*L>Wov%");
      Set<Worker> set0 = qualification0.getWorkers();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Qualification qualification0 = new Qualification("lP] SJ@Z6K\"*L>Wov%");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("lP] SJ@Z6K\"*L>Wov%", linkedHashSet0, 1488.2574682767674);
      qualification0.addWorker(worker0);
      qualification0.removeWorker(worker0);
      assertEquals("lP] SJ@Z6K\"*L>Wov%", qualification0.toString());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Qualification qualification0 = new Qualification("lP] SJ@Z6K\"*L>Wov%");
      String string0 = qualification0.toString();
      assertEquals("lP] SJ@Z6K\"*L>Wov%", string0);
  }
}
