/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 13 20:16:16 GMT 2026
 */

package edu.colostate.cs415.evosuite;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

import java.util.LinkedHashSet;
import java.util.Set;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.dto.WorkerDTO;
import edu.colostate.cs415.model.Project;
import edu.colostate.cs415.model.ProjectSize;
import edu.colostate.cs415.model.ProjectStatus;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Worker_ESTest extends Worker_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("@0h");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("@0h", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("@0h:0:1:0", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Project project1 = new Project("@0h", linkedHashSet0, projectSize0);
      boolean boolean0 = worker0.willOverload(project1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("@0h");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("@0h", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("@0h:0:1:0", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Project project1 = new Project("@0h", linkedHashSet0, projectSize0);
      worker0.addProject(project1);
      boolean boolean0 = worker0.willOverload(project1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("}SCh");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("@0h", linkedHashSet0, 0.0);
      worker0.setSalary(3404.22570956);
      assertEquals(3404.22570956, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("ey3An[Kh_o0%");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("ey3An[Kh_o0%", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("ey3An[Kh_o0%", linkedHashSet0, 0.0);
      worker0.addProject(project0);
      WorkerDTO workerDTO0 = worker0.toDTO();
      assertEquals(0.0, workerDTO0.getSalary(), 0.01);
      assertEquals(1, workerDTO0.getWorkload());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Dum;~P");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Dum;~P", linkedHashSet0, 1238.40041246758);
      WorkerDTO workerDTO0 = worker0.toDTO();
      assertEquals(0, workerDTO0.getWorkload());
      assertEquals(1238.40041246758, workerDTO0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("edu.colostate.cs415.dto.WorkerDTO");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("edu.colostate.cs415.dto.WorkerDTO", linkedHashSet0, 1025.22855233666);
      double double0 = worker0.getSalary();
      assertEquals(1025.22855233666, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Dum;~P");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Dum;~P", linkedHashSet0, 1238.40041246758);
      linkedHashSet0.clear();
      Set<Qualification> set0 = worker0.getQualifications();
      assertFalse(set0.contains(qualification0));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("@0h");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("@0h", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("@0h:0:1:0", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Set<Project> set0 = worker0.getProjects();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Worker cannot remove a null project");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Dum;~P", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        worker0.willOverload((Project) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      Worker worker0 = new Worker("edu.colostate.cs415.dto.WorkerDTO", linkedHashSet0, 1025.22855233666);
      // Undeclared exception!
      try { 
        worker0.toDTO();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.stream.ReferencePipeline$3$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("ey3An[Kh_o0%");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("ey3An[Kh_o0%", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("ey3An[Kh_o0%", linkedHashSet0, 0.0);
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      worker0.addProject(project0);
      int int0 = worker0.getWorkload();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Nv");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Nv", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("Null is not a valid description", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      int int0 = worker0.getWorkload();
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("}");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker(", status='", linkedHashSet0, 1818.3876694999);
      String string0 = worker0.getName();
      assertEquals(", status='", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Nv");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Nv", linkedHashSet0, 0.0);
      worker0.hashCode();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Nv");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Nv", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("Null is not a valid description", linkedHashSet0, projectSize0);
      boolean boolean0 = worker0.willOverload(project0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("ey3An[Kh_o0%");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("ey3An[Kh_o0%", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("ey3An[Kh_o0%", linkedHashSet0, 0.0);
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      worker0.addProject(project0);
      boolean boolean0 = worker0.isAvailable();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification(":");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker(":", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        worker0.removeProject((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker cannot remove a null project
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("ey3An[Kh_o0%");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("ey3An[Kh_o0%", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("ey3An[Kh_o0%", linkedHashSet0, 0.0);
      worker0.removeProject(project0);
      assertEquals(ProjectSize.SMALL, project0.getSize());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("EE*z2)");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("EE*z2)", linkedHashSet0, 1.0);
      // Undeclared exception!
      try { 
        worker0.addProject((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker cannot add a null project
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("[5Yk^kniJ/z");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("[5Yk^kniJ/z", linkedHashSet0, 519.12838);
      // Undeclared exception!
      try { 
        worker0.addQualification((Qualification) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker cannot add a null qualification
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Nv");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Nv", linkedHashSet0, 0.0);
      worker0.addQualification(qualification0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Nv");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Nv", linkedHashSet0, 0.0);
      worker0.setSalary(0.0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Nv");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Nv", linkedHashSet0, 0.0);
      worker0.setSalary((-661.8221362021345));
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("SUSPENDED");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("SUSPENDED", linkedHashSet0, 0.0);
      Worker worker1 = new Worker("DJm_=ZLP", linkedHashSet0, 12);
      boolean boolean0 = worker0.equals(worker1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("@0h");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("@0h", linkedHashSet0, 0.0);
      boolean boolean0 = worker0.equals(qualification0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("t!w[NYS*0b[@");
      linkedHashSet0.add(qualification0);
      Worker worker0 = null;
      try {
        worker0 = new Worker("t!w[NYS*0b[@", linkedHashSet0, (-21.3805));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker salary cannot be negative or NaN value
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = null;
      try {
        worker0 = new Worker("FIhQ*HED", linkedHashSet0, 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker Qualification set cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Worker worker0 = null;
      try {
        worker0 = new Worker("SUSPENDEcD", (Set<Qualification>) null, (-863.945));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker Qualification set cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = null;
      try {
        worker0 = new Worker("", linkedHashSet0, 1667.298);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker name cannot be empty or only whitespaces
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Worker worker0 = null;
      try {
        worker0 = new Worker((String) null, (Set<Qualification>) null, 2420.394);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker name cannot be null
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("ey3An[Kh_o0%");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("ey3An[Kh_o0%", linkedHashSet0, 0.0);
      Set<Project> set0 = worker0.getProjects();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("SUSPENDED");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("SUSPENDED", linkedHashSet0, 0.0);
      boolean boolean0 = worker0.equals(worker0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("@0h");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("@0h", linkedHashSet0, 0.0);
      String string0 = worker0.toString();
      assertEquals("@0h:0:1:0", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Worker cannot remove a null project");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Dum;~P", linkedHashSet0, 0.0);
      Set<Qualification> set0 = worker0.getQualifications();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("ey3An[Kh_o0%");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("ey3An[Kh_o0%", linkedHashSet0, 0.0);
      double double0 = worker0.getSalary();
      assertEquals(0.0, double0, 0.01);
  }
}
