/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 04:04:41 GMT 2026
 */

package edu.colostate.cs415.evosuite;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

import java.util.LinkedHashSet;
import java.util.Set;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.dto.WorkerDTO;
import edu.colostate.cs415.model.Project;
import edu.colostate.cs415.model.ProjectSize;
import edu.colostate.cs415.model.ProjectStatus;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Worker_ESTest extends Worker_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      Worker worker0 = new Worker("3i*!d>\")4$/qhIm:", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("&r[}iui", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Project project1 = new Project("cY''}@p", linkedHashSet0, projectSize0);
      worker0.addProject(project1);
      Project project2 = new Project("3i*!d>\")4$/qhIm:", linkedHashSet0, projectSize0);
      worker0.addProject(project2);
      Project project3 = new Project("~7rXg8my5Lm:r", linkedHashSet0, projectSize0);
      boolean boolean0 = worker0.willOverload(project3);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("s");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("s", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("edu.colostate.cs415.model.Worker", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Project project1 = new Project("s", linkedHashSet0, projectSize0);
      boolean boolean0 = worker0.willOverload(project1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      Worker worker0 = new Worker("3i*!d>\")4$/qhIm:", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("&r[}iui", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Project project1 = new Project("cY''}@p", linkedHashSet0, projectSize0);
      worker0.addProject(project1);
      Project project2 = new Project("3i*!d>\")4$/qhIm:", linkedHashSet0, projectSize0);
      worker0.addProject(project2);
      Project project3 = new Project("]b", linkedHashSet0, projectSize0);
      worker0.addProject(project3);
      boolean boolean0 = worker0.willOverload(project3);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("|o2f=2K/", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("|o2f=2K/", linkedHashSet0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      worker0.addProject(project0);
      boolean boolean0 = worker0.willOverload(project0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      Worker worker0 = new Worker("3i*!d>\")4$/qhIm:", linkedHashSet0, 0.0);
      worker0.setSalary(0.0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("|o2f=2K/", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("|o2f=2K/", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      WorkerDTO workerDTO0 = worker0.toDTO();
      assertEquals(0.0, workerDTO0.getSalary(), 0.01);
      assertEquals(1, workerDTO0.getWorkload());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("3na");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("3na", linkedHashSet0, 1.0);
      WorkerDTO workerDTO0 = worker0.toDTO();
      assertEquals(0, workerDTO0.getWorkload());
      assertEquals(1.0, workerDTO0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification(")lC]k+");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker(")lC]k+", linkedHashSet0, 0.0);
      double double0 = worker0.getSalary();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("3na");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("3na", linkedHashSet0, 1.0);
      LinkedHashSet<Qualification> linkedHashSet1 = new LinkedHashSet<Qualification>();
      linkedHashSet0.retainAll(linkedHashSet1);
      Set<Qualification> set0 = worker0.getQualifications();
      assertFalse(set0.contains(qualification0));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("|o2f=2K/", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("|o2f=2K/", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Set<Project> set0 = worker0.getProjects();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("xi");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("xi", linkedHashSet0, 1576.7349);
      // Undeclared exception!
      try { 
        worker0.willOverload((Project) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      Worker worker0 = new Worker("3i*!d>\")4$/qhIm:", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        worker0.toDTO();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.stream.ReferencePipeline$3$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("|o2f=2K/", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("|o2f=2K/", linkedHashSet0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      worker0.addProject(project0);
      int int0 = worker0.getWorkload();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("3na");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("3na", linkedHashSet0, 1.0);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("3na", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      int int0 = worker0.getWorkload();
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("xi");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("xi", linkedHashSet0, 1576.7349);
      worker0.hashCode();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("{ name='");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("A Worker salary cannot be negative or NaN value", linkedHashSet0, 3482.743816);
      Set<Qualification> set0 = worker0.getQualifications();
      assertTrue(set0.contains(qualification0));
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("A Worker salary cannot be negative or NaN value", linkedHashSet0, 3482.743816);
      boolean boolean0 = worker0.isAvailable();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      Worker worker0 = new Worker("3i*!d>\")4$/qhIm:", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("&r[}iui", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Project project1 = new Project("cY''}@p", linkedHashSet0, projectSize0);
      worker0.addProject(project1);
      Project project2 = new Project("3i*!d>\")4$/qhIm:", linkedHashSet0, projectSize0);
      worker0.addProject(project2);
      Project project3 = new Project("~7rXg8my5Lm:r", linkedHashSet0, projectSize0);
      worker0.addProject(project3);
      boolean boolean0 = worker0.isAvailable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      Worker worker0 = new Worker("3i*!d>g\")4$/qhIm:", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        worker0.removeProject((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker cannot remove a null project
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("A Worker salary cannot be negative or NaN value", linkedHashSet0, 3482.743816);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("A Worker salary cannot be negative or NaN value", linkedHashSet0, projectSize0);
      worker0.removeProject(project0);
      assertEquals("A Worker salary cannot be negative or NaN value", worker0.getName());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("|o2f=2(K/");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("|o2f=2(K/", linkedHashSet0, 0.7798622939923552);
      // Undeclared exception!
      try { 
        worker0.addProject((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker cannot add a null project
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("w");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("w", linkedHashSet0, 1.0);
      // Undeclared exception!
      try { 
        worker0.addQualification((Qualification) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker cannot add a null qualification
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("A Worker salary cannot be negative or NaN value", linkedHashSet0, 3482.743816);
      worker0.addQualification(qualification0);
      assertEquals(12, Worker.MAX_WORKLOAD);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("xi");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("xi", linkedHashSet0, 1576.7349);
      worker0.setSalary(1.0);
      assertEquals(1.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("A Worker salary cannot be negative or NaN value", linkedHashSet0, 3482.743816);
      worker0.setSalary((-2486.11));
      assertEquals(3482.743816, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("UF3m:");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("UF3m:", linkedHashSet0, 0.0);
      Worker worker1 = new Worker("HZ7T?", linkedHashSet0, 12);
      boolean boolean0 = worker0.equals(worker1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("A Worker salary cannot be negative or NaN value", linkedHashSet0, 3482.743816);
      Object object0 = new Object();
      boolean boolean0 = worker0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("UF3m:");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("UF3m:", linkedHashSet0, 0.0);
      boolean boolean0 = worker0.equals(worker0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("!+*Ed");
      linkedHashSet0.add(qualification0);
      Worker worker0 = null;
      try {
        worker0 = new Worker("!+*Ed", linkedHashSet0, (-980.704373582529));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker salary cannot be negative or NaN value
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = null;
      try {
        worker0 = new Worker("[#\"SWT!(ca<", linkedHashSet0, 3482.743816);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker Qualification set cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Worker worker0 = null;
      try {
        worker0 = new Worker("VThbAZg\"Z", (Set<Qualification>) null, (-4133.449420824));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker Qualification set cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = null;
      try {
        worker0 = new Worker("", linkedHashSet0, 2168.6787009219424);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker name cannot be empty or only whitespaces
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = null;
      try {
        worker0 = new Worker((String) null, linkedHashSet0, (-2489.4068445629373));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker name cannot be null
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("|o2f=2K/", linkedHashSet0, 0.0);
      Set<Project> set0 = worker0.getProjects();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("xi");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("xi", linkedHashSet0, 1576.7349);
      String string0 = worker0.getName();
      assertEquals("xi", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("|o2f=2K/", linkedHashSet0, 0.0);
      String string0 = worker0.toString();
      assertEquals("|o2f=2K/:0:1:0", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("A Worker salary cannot be negative or NaN value");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("A Worker salary cannot be negative or NaN value", linkedHashSet0, 3482.743816);
      double double0 = worker0.getSalary();
      assertEquals(3482.743816, double0, 0.01);
  }
}
