/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 28 00:00:46 GMT 2026
 */

package edu.colostate.cs415.model.evosuite_tests;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

import java.util.LinkedHashSet;
import java.util.Set;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.model.Company;
import edu.colostate.cs415.model.Project;
import edu.colostate.cs415.model.ProjectSize;
import edu.colostate.cs415.model.ProjectStatus;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Company_ESTest extends Company_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Company company0 = new Company(")%14(;`;b%9m^];>C");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification(")%14(;`;b%9m^];>C");
      linkedHashSet0.add(qualification0);
      company0.createWorker("teP%TN>%P-3tGI4Fq5", linkedHashSet0, 12);
      Set<Worker> set0 = company0.getUnassignedWorkers();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Company company0 = new Company("*=O$@8e2C1@2&^Nq,(E");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("XNyXH0Zxd!Uut;bwXE", linkedHashSet0, projectSize0);
      Set<Project> set0 = company0.getProjects();
      assertTrue(set0.contains(project0));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Company company0 = new Company(", salary='");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification(", salary='");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker(", salary='", linkedHashSet0, 146.4247263486751);
      Set<Worker> set0 = company0.getEmployedWorkers();
      assertTrue(set0.contains(worker0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Company company0 = new Company(", salary='");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("4+-");
      linkedHashSet0.add(qualification0);
      company0.createWorker("edu.colostate.cs415.model.Company", linkedHashSet0, 146.4247263486751);
      Set<Worker> set0 = company0.getAvailableWorkers();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Company company0 = new Company("|!^");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("|!^");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("|!^", linkedHashSet0, projectSize0);
      Worker worker0 = company0.createWorker("MS~q]b", linkedHashSet0, 1.0);
      company0.assign(worker0, project0);
      Set<Worker> set0 = company0.getAssignedWorkers();
      assertTrue(set0.contains(worker0));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Company company0 = new Company("9kU]oT-6JV");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createQualification("{~~");
      Worker worker0 = company0.createWorker("x?", set0, 0.0);
      assertEquals("x?", worker0.getName());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Company company0 = new Company("CGqA");
      // Undeclared exception!
      try { 
        company0.finish((Project) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Company company0 = new Company("A Worker salary cannot be negative or NaN value");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = new Worker("A Worker salary cannot be negative or NaN value", set0, 1.0);
      worker0.addQualification((Qualification) null);
      // Undeclared exception!
      try { 
        company0.createWorker("PLANNED", set0, 648.8641845120154);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      // Undeclared exception!
      try { 
        company0.createProject("", set0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project name cannot be empty
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Company company0 = new Company("{4+-");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = company0.createQualification("{4+-");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker(";MijLx@(<2at{m#86", linkedHashSet0, 4549.728);
      // Undeclared exception!
      try { 
        company0.assign(worker0, (Project) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("gX?+^(evWb[", set0, projectSize0);
      company0.createProject("gX?+^(evWb[", set0, projectSize0);
      Worker worker0 = company0.createWorker(";MijLx@(<2at{m#86", set0, 1.0);
      company0.assign(worker0, project0);
      company0.start(project0);
      company0.unassign(worker0, project0);
      assertEquals(ProjectStatus.SUSPENDED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("gX?+^(evWb[", set0, projectSize0);
      Worker worker0 = company0.createWorker(";MijLx@(<2at{m#86", set0, 1.0);
      company0.assign(worker0, project0);
      company0.unassign(worker0, project0);
      assertEquals(ProjectSize.BIG, project0.getSize());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Company company0 = new Company("HfpcAjU/O1&Q");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("32^EU]5z%N4M\"j,bb|x", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("32^EU]5z%N4M\"j,bb|x", linkedHashSet0, 633.64760319441);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Company company0 = new Company("/:G<^xQ/r44");
      company0.createQualification("/:G<^xQ/r44");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("/:G<^xQ/r44", set0, 543.4365);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("/:G<^xQ/r44", set0, projectSize0);
      company0.assign(worker0, project0);
      company0.unassignAll(worker0);
      assertEquals("/:G<^xQ/r44", worker0.getName());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Company company0 = new Company("A Worker salary cannot be negative or NaN value");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = new Worker("A Worker salary cannot be negative or NaN value", set0, 1.0);
      // Undeclared exception!
      try { 
        company0.unassignAll(worker0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Company company0 = new Company("OpERnJ6F*");
      // Undeclared exception!
      try { 
        company0.unassignAll((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("gX?+^(evWb[", set0, projectSize0);
      Worker worker0 = company0.createWorker("gX?+^(evWb[", set0, 2646.142885304427);
      company0.assign(worker0, project0);
      company0.start(project0);
      company0.unassignAll(worker0);
      assertEquals(12, Worker.MAX_WORKLOAD);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("gX?+^(evWb[", set0, projectSize0);
      Worker worker0 = company0.createWorker("gX?+^(evWb[", set0, 2646.142885304427);
      project0.addWorker(worker0);
      company0.unassign(worker0, project0);
      assertEquals("gX?+^(evWb[", company0.getName());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Company company0 = new Company(", salary='");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project(", salary='", linkedHashSet0, projectSize0);
      Qualification qualification0 = company0.createQualification(", salary='");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker(", salary='", linkedHashSet0, 146.4247263486751);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("gX?+^(evWb[", set0, projectSize0);
      Worker worker0 = company0.createWorker(";MijLx@(<2at{m#86", set0, 1.0);
      company0.unassign(worker0, project0);
      assertEquals(1.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Company company0 = new Company("7\"m&kkY&v");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = new Worker("7\"m&kkY&v:0:0", set0, 0.0);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Company company0 = new Company("A Workersalary cannot be fegative or NaN value");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("A Workersalary cannot be fegative or NaN value:0:0", set0, projectSize0);
      // Undeclared exception!
      try { 
        company0.unassign((Worker) null, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("gX?+^(evWb[", set0, projectSize0);
      Worker worker0 = company0.createWorker(";MijLx@(<2at{m#86", set0, 1.0);
      company0.assign(worker0, project0);
      Worker worker1 = company0.createWorker("Must be a valid ProjectStatus", set0, 1.0);
      assertNotNull(worker1);
      
      company0.assign(worker1, project0);
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("gX?+^(evWb[", set0, projectSize0);
      Worker worker0 = company0.createWorker(";MijLx@(<2at{m#86", set0, 1.0);
      assertNotNull(worker0);
      
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      company0.assign(worker0, project0);
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("gX?+^(evWb[", set0, projectSize0);
      Worker worker0 = company0.createWorker("gX?+^(evWb[", set0, 2646.142885304427);
      assertNotNull(worker0);
      
      company0.assign(worker0, project0);
      company0.assign(worker0, project0);
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("gX?+^(evWb[", set0, projectSize0);
      Worker worker0 = company0.createWorker(";MijLx@(<2at{m#86", set0, 1.0);
      company0.assign(worker0, project0);
      company0.start(project0);
      Worker worker1 = company0.createWorker("Must be a valid ProjectStatus", set0, 1.0);
      company0.assign(worker1, project0);
      assertEquals(ProjectStatus.ACTIVE, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Company company0 = new Company("9kU]oT-6JV");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("9kU]oT-6JV", set0, projectSize0);
      company0.assign((Worker) null, project0);
      assertEquals(ProjectSize.MEDIUM, project0.getSize());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Company company0 = new Company("OP_[Ebzec#O6oe0w");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("OP_[Ebzec#O6oe0w", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("{4+-", linkedHashSet0, 1.0);
      project0.addWorker(worker0);
      company0.start(project0);
      // Undeclared exception!
      try { 
        company0.finish(project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Company company0 = new Company("{4+-");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("{4+-", linkedHashSet0, projectSize0);
      company0.start(project0);
      company0.finish(project0);
      assertEquals(ProjectStatus.FINISHED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("gX?+^(evWb[", set0, projectSize0);
      company0.finish(project0);
      assertEquals(ProjectStatus.PLANNED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("gX?+^(evWb[", set0, projectSize0);
      company0.start(project0);
      assertEquals(ProjectStatus.PLANNED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Company company0 = new Company("A Worker salary cannot be negative or NaN value");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("A Worker salary cannot be negative or NaN value:0:0", set0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.SUSPENDED;
      project0.setStatus(projectStatus0);
      company0.start(project0);
      assertEquals(ProjectStatus.ACTIVE, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Company company0 = new Company("{4+-");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("{4+-", linkedHashSet0, projectSize0);
      company0.start(project0);
      company0.start(project0);
      assertEquals(ProjectStatus.ACTIVE, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Company company0 = new Company("pe^Wn#_'");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = company0.createProject("pe^Wn#_'", linkedHashSet0, projectSize0);
      Company company1 = new Company("ILiL4*W(");
      // Undeclared exception!
      try { 
        company1.start(project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Company company0 = new Company("kF}%h/E^+,r");
      // Undeclared exception!
      try { 
        company0.start((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Company company0 = new Company("9kU]oT-6JV");
      Qualification qualification0 = company0.createQualification("");
      assertNull(qualification0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Company company0 = new Company("pe^Wn#_'");
      Qualification qualification0 = company0.createQualification((String) null);
      assertNull(qualification0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Company company0 = new Company("OpERnJ6F*");
      Qualification qualification0 = new Qualification("h<p3");
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("h<p3", linkedHashSet0, 301.9268765363);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createWorker("VK2j0yH#w^t", set0, (-126.7211345712087));
      assertFalse(set0.isEmpty());
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Company company0 = new Company("9kU]oT-6JV");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("9kU]oT-6JV", set0, 27.619502785882073);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Company company0 = new Company("o");
      Worker worker0 = company0.createWorker("o", (Set<Qualification>) null, 1.2432093311783146);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Company company0 = new Company("edu.colostatecs415.model.ProjectStatus");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("", set0, 1.0);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Company company0 = new Company("/:G<^xQ/r44");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker((String) null, set0, 543.4365);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      company0.createQualification("gX?+^(evWb[");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker(";MijLx@(<2at{m#86", set0, 1.0);
      assertNotNull(worker0);
      
      Set<Worker> set1 = company0.getUnavailableWorkers();
      assertFalse(set1.contains(worker0));
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Company company0 = new Company("pe^Wn#_'");
      Company company1 = new Company("ILiL4*W(");
      boolean boolean0 = company0.equals(company1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Company company0 = new Company("OP_[Ebzec#O6oe0w");
      Object object0 = new Object();
      boolean boolean0 = company0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Company company0 = new Company("OP_[Ebzec#O6oe0w");
      boolean boolean0 = company0.equals(company0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Company company0 = null;
      try {
        company0 = new Company("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Company company0 = null;
      try {
        company0 = new Company((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      Set<Worker> set0 = company0.getAvailableWorkers();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      Set<Project> set0 = company0.getProjects();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Company company0 = new Company(".E3T|");
      Set<Worker> set0 = company0.getAssignedWorkers();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Company company0 = new Company("A Worker salary cannot be negative or NaN value");
      company0.hashCode();
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      Set<Worker> set0 = company0.getUnassignedWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Company company0 = new Company("gX?+^(evWb[");
      String string0 = company0.toString();
      assertEquals("gX?+^(evWb[:0:0", string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Company company0 = new Company("OP_[Ebzec#O6oe0w");
      Set<Worker> set0 = company0.getEmployedWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Company company0 = new Company(".E3T|");
      String string0 = company0.getName();
      assertEquals(".E3T|", string0);
  }
}
