/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 28 00:01:49 GMT 2026
 */

package edu.colostate.cs415.model.evosuite_tests;

import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.model.ProjectSize;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProjectSize_ESTest extends ProjectSize_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProjectSize[] projectSizeArray0 = ProjectSize.values();
      assertEquals(3, projectSizeArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProjectSize projectSize0 = ProjectSize.valueOf("SMALL");
      assertEquals(ProjectSize.SMALL, projectSize0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProjectSize projectSize0 = ProjectSize.SMALL;
      int int0 = projectSize0.getValue();
      assertEquals(1, int0);
  }
}
