/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 27 23:58:36 GMT 2026
 */

package edu.colostate.cs415.model.evosuite_tests;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

import java.util.LinkedHashSet;
import java.util.Set;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.dto.ProjectDTO;
import edu.colostate.cs415.model.Project;
import edu.colostate.cs415.model.ProjectSize;
import edu.colostate.cs415.model.ProjectStatus;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Project_ESTest extends Project_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("FqCCpw&Qa|%!", linkedHashSet0, 1.0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("h", linkedHashSet0, projectSize0);
      project0.addWorker(worker0);
      Set<Worker> set0 = project0.getWorkers();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("edu.colostate.cs415.model.Qualification");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("edu.colostate.cs415.model.Qualification", linkedHashSet0, projectSize0);
      Set<Qualification> set0 = project0.getRequiredQualifications();
      assertTrue(set0.contains(qualification0));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("edu.colostate.cs415.model.Qualification");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("edu.colostate.cs415.model.Qualification", linkedHashSet0, projectSize0);
      Set<Qualification> set0 = project0.getMissingQualifications();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(3201);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      linkedHashSet0.add((Qualification) null);
      Project project0 = new Project("82bRq<8R*,g'(", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.toDTO();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.stream.ReferencePipeline$3$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("g,cw~ege", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("g,cw~ege", linkedHashSet0, 0.0);
      project0.addWorker(worker0);
      Set<Qualification> set0 = project0.getMissingQualifications();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("@Aq", linkedHashSet0, projectSize0);
      String string0 = project0.getName();
      assertEquals("@Aq", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("h|ggP2Zu9jyw@B3dtcJ", linkedHashSet0, 0.6425624484022733);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("h|ggP2Zu9jyw@B3dtcJ", linkedHashSet0, projectSize0);
      Qualification qualification0 = new Qualification("h|ggP2Zu9jyw@B3dtcJ");
      linkedHashSet0.add(qualification0);
      boolean boolean0 = project0.isHelpful(worker0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("gL%{rhvz>7EFewm");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("gL%{rhvz>7EFewm", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("Must be a valid ProjectStatus", linkedHashSet0, 2430.27719352645);
      boolean boolean0 = project0.isHelpful(worker0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("wJZ#mn", linkedHashSet0, projectSize0);
      boolean boolean0 = project0.isHelpful((Worker) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("$(lz;H:", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.addQualification((Qualification) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be a valid qualification
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("gL%{rhvz>7EFewm");
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("gL%{rhvz>7EFewm", linkedHashSet0, projectSize0);
      project0.addQualification(qualification0);
      assertEquals(ProjectStatus.PLANNED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("?8eQIN6j>0!:jx-", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.removeWorker((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be a valid worker
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("gL%{rhvz>7EFewm", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("Must be a valid ProjectStatus", linkedHashSet0, 2430.27719352645);
      project0.removeWorker(worker0);
      assertEquals("gL%{rhvz>7EFewm", project0.getName());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("edu.colostate.cs415.model.Qualification", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.addWorker((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be a valid worker
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("iS4WSxEPA^xDZ^ue3v", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("iS4WSxEPA^xDZ^ue3v", linkedHashSet0, 23.2740725851);
      project0.addWorker(worker0);
      ProjectDTO projectDTO0 = project0.toDTO();
      assertEquals("iS4WSxEPA^xDZ^ue3v", projectDTO0.getName());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project(":", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.setStatus((ProjectStatus) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be a valid ProjectStatus
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("h|ggP2Zu9jyw@B3dtcJ", linkedHashSet0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      assertEquals("h|ggP2Zu9jyw@B3dtcJ", project0.getName());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("iS4WSxEPA^xDZ^ue3v", linkedHashSet0, projectSize0);
      Project project1 = new Project("ihSWIa;SOkPzWZul3)", linkedHashSet0, projectSize0);
      boolean boolean0 = project0.equals(project1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("h|ggP2Zu9jyw@B3dtcJ", linkedHashSet0, 0.6425624484022733);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("h|ggP2Zu9jyw@B3dtcJ", linkedHashSet0, projectSize0);
      boolean boolean0 = project0.equals(worker0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Project project0 = null;
      try {
        project0 = new Project("Must be a valid worker", linkedHashSet0, (ProjectSize) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project size cannot be null
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = null;
      try {
        project0 = new Project(", missingQuallfications='", (Set<Qualification>) null, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project qualifications cannot be null
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = null;
      try {
        project0 = new Project(" ", linkedHashSet0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project name cannot be empty
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = null;
      try {
        project0 = new Project((String) null, linkedHashSet0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project name cannot be null
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("?8eQIN6j>0!:jx-", linkedHashSet0, projectSize0);
      Set<Worker> set0 = project0.getWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("?8eQIN6j>0!:jx-", linkedHashSet0, projectSize0);
      Set<Qualification> set0 = project0.getRequiredQualifications();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("iS4WSxEPA^xDZ^ue3v", linkedHashSet0, projectSize0);
      ProjectStatus projectStatus0 = project0.getStatus();
      assertEquals(ProjectStatus.PLANNED, projectStatus0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("h|ggP2Zu9jyw@B3dtcJ", linkedHashSet0, projectSize0);
      ProjectSize projectSize1 = project0.getSize();
      assertEquals(2, projectSize1.getValue());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("iS4WSxEPA^xDZ^ue3v", linkedHashSet0, projectSize0);
      boolean boolean0 = project0.equals(project0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("?8eQIN6j>0!:jx-", linkedHashSet0, projectSize0);
      project0.hashCode();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("wJZ#mn", linkedHashSet0, projectSize0);
      String string0 = project0.toString();
      assertEquals("wJZ#mn:0:PLANNED", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("?8eQIN6j>0!:jx-", linkedHashSet0, projectSize0);
      project0.removeAllWorkers();
      assertEquals(ProjectSize.BIG, project0.getSize());
  }
}
