/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 27 23:59:40 GMT 2026
 */

package edu.colostate.cs415.model.evosuite_tests;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

import java.util.Set;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.dto.QualificationDTO;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Qualification_ESTest extends Qualification_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Qualification qualification0 = new Qualification("iG&Ns}4hB[n<");
      Qualification qualification1 = new Qualification("iG&Ns}4hB[n<");
      boolean boolean0 = qualification0.equals(qualification1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Qualification qualification0 = new Qualification("KBS7I{sh");
      qualification0.addWorker((Worker) null);
      Set<Worker> set0 = qualification0.getWorkers();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Qualification qualification0 = new Qualification("P)~y3`j?}O");
      qualification0.addWorker((Worker) null);
      // Undeclared exception!
      try { 
        qualification0.toDTO();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.stream.ReferencePipeline$3$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Qualification qualification0 = null;
      try {
        qualification0 = new Qualification((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null is not a valid description
         //
         verifyException("edu.colostate.cs415.model.Qualification", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Qualification qualification0 = new Qualification("Must be a valid worker");
      qualification0.removeWorker((Worker) null);
      assertEquals("Must be a valid worker", qualification0.toString());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Qualification qualification0 = null;
      try {
        qualification0 = new Qualification("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null is not a valid description
         //
         verifyException("edu.colostate.cs415.model.Qualification", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Qualification qualification0 = new Qualification("Must be a valid worker");
      QualificationDTO qualificationDTO0 = qualification0.toDTO();
      assertEquals("Must be a valid worker", qualificationDTO0.getDescription());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Qualification qualification0 = new Qualification("Must be a valid worker");
      Set<Worker> set0 = qualification0.getWorkers();
      boolean boolean0 = qualification0.equals(set0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Qualification qualification0 = new Qualification("Must be a valid worker");
      qualification0.addWorker((Worker) null);
      qualification0.removeWorker((Worker) null);
      assertEquals("Must be a valid worker", qualification0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Qualification qualification0 = new Qualification("Must be a valid worker");
      qualification0.hashCode();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Qualification qualification0 = new Qualification("Must be a valid worker");
      String string0 = qualification0.toString();
      assertEquals("Must be a valid worker", string0);
  }
}
