/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 27 23:57:31 GMT 2026
 */

package edu.colostate.cs415.model.evosuite_tests;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

import java.util.LinkedHashSet;
import java.util.Set;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import edu.colostate.cs415.dto.WorkerDTO;
import edu.colostate.cs415.model.Project;
import edu.colostate.cs415.model.ProjectSize;
import edu.colostate.cs415.model.ProjectStatus;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Worker_ESTest extends Worker_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(59, 59);
      Worker worker0 = new Worker("$<lbA?FB:", linkedHashSet0, 59);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("edu.colostate.cs415.model.Project", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      ProjectSize projectSize1 = ProjectSize.BIG;
      Project project1 = new Project("qm", linkedHashSet0, projectSize1);
      worker0.addProject(project1);
      Project project2 = new Project("$<lRWAM4<", linkedHashSet0, projectSize1);
      worker0.addProject(project2);
      Project project3 = new Project("$<lbA?FB:", linkedHashSet0, projectSize1);
      worker0.addProject(project3);
      Project project4 = new Project("q@EF", linkedHashSet0, projectSize1);
      worker0.addProject(project4);
      boolean boolean0 = worker0.isAvailable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(12, 1246.0F);
      Worker worker0 = new Worker("$<lRxAM4:", linkedHashSet0, 1246.0F);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("$<lRxAM4:", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Project project1 = new Project(";&lu;6qlm9p2_wD", linkedHashSet0, projectSize0);
      worker0.addProject(project1);
      Project project2 = new Project("qEE@", linkedHashSet0, projectSize0);
      worker0.addProject(project2);
      boolean boolean0 = worker0.willOverload(project1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("_OGF{X`AilAFK", linkedHashSet0, 0.0);
      worker0.setSalary(12);
      assertEquals(12.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("Project qualifications cannot be null", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("Project qualifications cannot be null", linkedHashSet0, 0.0);
      worker0.addProject(project0);
      WorkerDTO workerDTO0 = worker0.toDTO();
      assertEquals(0.0, workerDTO0.getSalary(), 0.01);
      assertEquals(1, workerDTO0.getWorkload());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("Project qualifications cannot be null", linkedHashSet0, 0.0);
      WorkerDTO workerDTO0 = worker0.toDTO();
      assertEquals(0, workerDTO0.getWorkload());
      assertEquals(0.0, workerDTO0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("Project qualifications cannot be null", linkedHashSet0, 0.0);
      double double0 = worker0.getSalary();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("!dbdu:96Gr=pm`>", linkedHashSet0, 1824.1197);
      Qualification qualification0 = new Qualification("CLcAz~J ~,'_");
      worker0.addQualification(qualification0);
      Set<Qualification> set0 = worker0.getQualifications();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("9`2o", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      worker0.addProject(project0);
      Set<Project> set0 = worker0.getProjects();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("x,*pGW", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        worker0.willOverload((Project) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("5\"[L", linkedHashSet0, 1366.32529353);
      worker0.addQualification((Qualification) null);
      // Undeclared exception!
      try { 
        worker0.toDTO();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.stream.ReferencePipeline$3$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("A Worker name cannot be null", linkedHashSet0, 3019.841);
      worker0.addProject((Project) null);
      // Undeclared exception!
      try { 
        worker0.isAvailable();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(12, 1246.1492F);
      Worker worker0 = new Worker(";&lu;6qlm9p2_wD", linkedHashSet0, 1246.1492F);
      worker0.addProject((Project) null);
      // Undeclared exception!
      try { 
        worker0.getWorkload();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("RsrvHA(MS (s\\2EV|T", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      worker0.addProject(project0);
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      int int0 = worker0.getWorkload();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("RsrvHA(MS (s\\2EV|T", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      worker0.addProject(project0);
      int int0 = worker0.getWorkload();
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("Project qualifications cannot be null", linkedHashSet0, 0.0);
      String string0 = worker0.getName();
      assertEquals("Project qualifications cannot be null", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(12, 1246.0F);
      Worker worker0 = new Worker("$<lRWAM4<", linkedHashSet0, 1246.0F);
      worker0.hashCode();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(12, 1246.0F);
      Worker worker0 = new Worker("$<lRWAM4<", linkedHashSet0, 1246.0F);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("qm", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Project project1 = new Project("$<lRWAM4<", linkedHashSet0, projectSize0);
      worker0.addProject(project1);
      Project project2 = new Project(";&lu;6qlm9p2_wD", linkedHashSet0, projectSize0);
      worker0.addProject(project2);
      Project project3 = new Project("qEE@", linkedHashSet0, projectSize0);
      worker0.addProject(project3);
      boolean boolean0 = worker0.isAvailable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(12, 1246.0F);
      Worker worker0 = new Worker("$<lRWAM4<", linkedHashSet0, 1246.0F);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("qm", linkedHashSet0, projectSize0);
      worker0.addProject(project0);
      Project project1 = new Project("$<lRWAM4<", linkedHashSet0, projectSize0);
      worker0.addProject(project1);
      Project project2 = new Project(";&lu;6qlm9p2_wD", linkedHashSet0, projectSize0);
      worker0.addProject(project2);
      Project project3 = new Project("qEE@", linkedHashSet0, projectSize0);
      worker0.addProject(project3);
      boolean boolean0 = worker0.willOverload(project2);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("RsrvHA(MS (s\\2EV|T", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      boolean boolean0 = worker0.willOverload(project0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("RsrvHA(MS (s\\2EV|T", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      worker0.addProject(project0);
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      WorkerDTO workerDTO0 = worker0.toDTO();
      assertEquals(0, workerDTO0.getWorkload());
      assertEquals(4905.8232819621, workerDTO0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("5\"[L", linkedHashSet0, 1366.32529353);
      worker0.setSalary(0.0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("V;C=bXrd/+", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        worker0.setSalary((-2443.905));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker salary cannot be negative or NaN value
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>(12, 1246.0F);
      Worker worker0 = new Worker("$<lRWAM4<", linkedHashSet0, 1246.0F);
      Worker worker1 = new Worker("$<lbA?FB:", linkedHashSet0, 1246.0F);
      boolean boolean0 = worker1.equals(worker0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      boolean boolean0 = worker0.equals("9`2o");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = null;
      try {
        worker0 = new Worker("9`2o:0:0:4905", linkedHashSet0, (-3908.178332));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker salary cannot be negative or NaN value
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Worker worker0 = null;
      try {
        worker0 = new Worker("$<lbA?B:", (Set<Qualification>) null, 4400.55256987);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker Qualification set cannot be null
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Worker worker0 = null;
      try {
        worker0 = new Worker("", (Set<Qualification>) null, 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker name cannot be empty or only whitespaces
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = null;
      try {
        worker0 = new Worker((String) null, linkedHashSet0, (-28.66578683997132));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A Worker name cannot be null
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      Set<Project> set0 = worker0.getProjects();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      boolean boolean0 = worker0.equals(worker0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      String string0 = worker0.toString();
      assertEquals("9`2o:0:0:4905", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("RsrvHA(MS (s\\2EV|T", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      worker0.removeProject(project0);
      assertEquals("RsrvHA(MS (s\\2EV|T", project0.getName());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      Set<Qualification> set0 = worker0.getQualifications();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("RsrvHA(MS (s\\2EV|T", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      worker0.addProject(project0);
      boolean boolean0 = worker0.isAvailable();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = new Worker("9`2o", linkedHashSet0, 4905.8232819621);
      double double0 = worker0.getSalary();
      assertEquals(4905.8232819621, double0, 0.01);
  }
}
